#定义开发模式，方便调用日志
name: "Panopeia"
mode: "dev"
start_time: "2022-05-01"
machine_id: 1

#Log 配置
log:
  level: "debug"
  filename: "system.log"
  max_size: 200
  max_age: 30
  max_backups: 7
#DB 配置
DB:
  name: test
  user: root
  password: www.nas.beer
  ip: 43.134.14.101
  port: 8100
  dbName: test
  charset: utf8mb4
  maxIdle: 10
  maxOpen: 20
  maxLiftTime: 3600000

